import { useRouter } from 'expo-router';
import { View, Text, Image, ScrollView } from 'react-native';
import {
  ArrowRight,
  Barbell,
  Lightning,
  Target,
  TrendUp,
  Trophy,
  Users,
} from 'phosphor-react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Button } from '@/components/ui';

export default function OnBoarding() {
  const router = useRouter();

  const features = [
    {
      icon: <Barbell size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Ai Plans',
      description: 'Personalized workout plans generated by artificial intelligence',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
    {
      icon: <Target size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Goal Tracking',
      description: 'Set and track your fitness goals with detailed analytics',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
    {
      icon: <TrendUp size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Progress Analytics',
      description: 'Visualize your progress with beautiful charts and insights',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
    {
      icon: <Users size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Community',
      description: 'Connect with like-minded fitness enthusiasts',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
  ];

  const achievements = [
    {
      icon: <Users size={40} color={'#8AB4F8'} />,
      value: '50K+',
      label: 'Active Users',
    },
    {
      icon: <Lightning size={40} color={'#8AB4F8'} />,
      value: '1M+',
      label: 'Workouts Completed',
    },
    {
      icon: <Trophy size={40} color={'#8AB4F8'} />,
      value: '95%',
      label: 'Satisfaction Rate',
    },
  ];

  return (
    <ScrollView className="flex-1 bg-background">
      {/* Hero Section */}
      <View className="min-h-screen flex-1">
        <LinearGradient
          colors={['#1a1a1a', '#F7F7F7', '#1a1a1a']}
          start={{ x: 0, y: 0 }}
          end={{ x: 0, y: 1 }}
          style={{ flex: 1, width: '100%' }}>
          {/* Main content container */}
          <View className="flex-1 items-center justify-center px-8 py-14">
            {/* Title and subtitle */}
            <View className="mb-5">
              <Text className="mb-8 text-center text-5xl font-bold leading-tight text-background">
                Transform Your{'\n'}Fitness Journey
              </Text>

              <Text className="mb-2 max-w-sm text-center text-lg leading-relaxed text-black/60">
                AI-powered workouts, personalized nutrition, and progress tracking
              </Text>
            </View>

            {/* Action buttons */}
            <View className="mb-12 w-full max-w-sm px-4">
              <View className="mb-4">
                <Button
                  size="lg"
                  text="Get Started"
                  onPress={() => router.push('/sign-up')}
                  className="w-full bg-white shadow-lg"
                  icon={<ArrowRight color="#111827" size={20} />}
                />
              </View>
              <View>
                <Button
                  size="lg"
                  text="Sign In"
                  onPress={() => router.push('/login')}
                  className="w-full border-2 border-gray-400 bg-white/10 backdrop-blur-sm"
                />
              </View>
            </View>

            {/* Hero image */}
            <View className="relative h-60 w-80 overflow-hidden rounded-3xl shadow-2xl">
              <Image
                source={{
                  uri: 'https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=2',
                }}
                className="h-full w-full rounded-3xl"
              />
              <LinearGradient
                colors={['transparent', '#00000060']}
                className="absolute bottom-0 left-0 right-0 h-2/3"
              />

              {/* Image overlay content */}
              <View className="absolute bottom-4 left-4 right-4">
                <Text className="text-sm font-medium text-white/90">
                  Start your transformation today
                </Text>
              </View>
            </View>
          </View>
        </LinearGradient>
      </View>

      {/* Features Section */}
      <View className="my-8 px-6">
        <Text className="mb-2 text-center text-xl font-bold text-textPrimary">
          Everything You Need
        </Text>
        <Text className="mb-6 text-center text-sm text-textSecondary">
          Personalized workout plans generated by artificial intelligence
        </Text>

        <View className="flex-row flex-wrap justify-between gap-y-4">
          {features.map((feature, index) => (
            <View key={index} className="w-[48%]  rounded-lg bg-surface p-3">
              <View className="mb-4 items-center justify-center rounded-full bg-white/10 p-2">
                {feature.icon}
              </View>
              <Text className="mb-2 text-center text-lg font-bold text-textPrimary">
                {feature.title}
              </Text>
              <Text className="text-center text-sm text-textSecondary">{feature.description}</Text>
            </View>
          ))}
        </View>
      </View>

      {/* Stats Section */}
      <View className="flex-row justify-around gap-4 bg-surface p-4">
        {achievements.map((achievement, index) => (
          <View key={index} className="flex-1 items-center justify-center gap-3">
            <View className="max-h-12 max-w-12">{achievement.icon}</View>
            <Text className="text-lg font-bold text-textPrimary">{achievement.value}</Text>
            <Text className="text-wrap text-center text-xs uppercase tracking-wider text-textSecondary">
              {achievement.label}
            </Text>
          </View>
        ))}
      </View>

      {/* Footer */}
      <View className="mb-5 items-center py-5">
        <Text className="text-center text-sm text-textSecondary">
          © 2024 FitFlow. All rights reserved.
        </Text>
      </View>
    </ScrollView>
  );
}
