import { useRouter } from 'expo-router';
import { ScrollView, Image, View, Text } from 'react-native';
import {
  ArrowRight,
  Barbell,
  Lightning,
  Star,
  Target,
  TrendUp,
  Trophy,
  Users,
} from 'phosphor-react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Button, Card } from '@/components/ui';

export default function OnBoarding() {
  const router = useRouter();

  const features = [
    {
      icon: <Barbell size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Everything You Need',
      description: 'Personalized workout plans generated by artificial intelligence',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
    {
      icon: <Target size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Goal Tracking',
      description: 'Set and track your fitness goals with detailed analytics',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
    {
      icon: <TrendUp size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Progress Analytics',
      description: 'Visualize your progress with beautiful charts and insights',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
    {
      icon: <Users size={32} weight="duotone" color={'#f9c04a'} />,
      title: 'Community',
      description: 'Connect with like-minded fitness enthusiasts',
      gradient: ['#f9c04a20', '#f9c04a10'],
    },
  ];

  const testimonials = [
    {
      name: 'Sarah Johnson',
      rating: 5,
      text: 'FitFlow transformed my fitness journey. The AI workouts are incredible!',
      image:
        'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      role: 'Fitness Enthusiast',
    },
    {
      name: 'Mike Chen',
      rating: 5,
      text: "Best fitness app I've ever used. The progress tracking is amazing.",
      image:
        'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      role: 'Personal Trainer',
    },
    {
      name: 'Emma Davis',
      rating: 5,
      text: 'Love the personalized nutrition plans. Finally seeing real results!',
      image:
        'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
      role: 'Nutritionist',
    },
  ];

  const achievements = [
    {
      icon: <Users size={24} color={'#f9c04a'} />,
      value: '50K+',
      label: 'Active Users',
    },
    {
      icon: <Lightning size={24} color={'#f9c04a'} />,
      value: '1M+',
      label: 'Workouts Completed',
    },
    {
      icon: <Trophy size={24} color={'#f9c04a'} />,
      value: '95%',
      label: 'Satisfaction Rate',
    },
  ];

  return (
    <ScrollView showsVerticalScrollIndicator={false} className="flex-1 bg-background pt-16">
      {/* Hero Section */}
      <Card className="mb-8 overflow-hidden p-0">
        <LinearGradient
          colors={['#60A5FA', '#A78BFA', '#22D3EE']}
          className="relative p-6"
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}>
          <View className="absolute inset-0">
            <View className="absolute right-[10%] top-[10%] h-20 w-20 rounded-full bg-white/10" />
            <View className="h-15 w-15 absolute left-[5%] top-[60%] rounded-full bg-white/10" />
            <View className="absolute right-[30%] top-[30%] h-10 w-10 rounded-full bg-white/10" />
          </View>

          <View className="items-center">
            <Text className="mb-3 text-center text-4xl font-bold text-white">
              Transform Your Fitness Journey
            </Text>

            <Text className="mb-6 text-center text-white/90">
              AI-powered workouts, personalized nutrition, and progress tracking all in one app
            </Text>

            <View className="mb-6 flex-row gap-4">
              <Button
                onPress={() => router.push('/sign-up')}
                className="flex-row items-center gap-2">
                <Text className="text-primary-dark">Get Started</Text>
                <ArrowRight color="#000000" size={20} />
              </Button>

              <Button
                variant="outline"
                onPress={() => router.push('/login')}
                className="border-white/30 bg-white/10">
                <Text className="text-white">Sign In</Text>
              </Button>
            </View>

            <View className="overflow-hidden rounded-2xl">
              <Image
                source={{
                  uri: 'https://images.pexels.com/photos/416778/pexels-photo-416778.jpeg?auto=compress&cs=tinysrgb&w=800&h=600&dpr=2',
                }}
                className="h-48 w-full"
                resizeMode="cover"
              />
              <LinearGradient
                colors={['transparent', '#00000040']}
                className="absolute bottom-0 left-0 right-0 h-1/2"
              />
            </View>
          </View>
        </LinearGradient>
      </Card>

      {/* Features Section */}
      <View className="mb-8">
        <Text className="mb-2 text-center text-2xl font-bold">Everything You Need</Text>
        <Text className="mb-6 text-center text-sm text-text-secondary">
          Personalized workout plans generated by artificial intelligence
        </Text>

        <View className="flex-row flex-wrap justify-between gap-y-4">
          {features.map((feature, index) => (
            <Card key={index} className="w-[48%] p-0" onPress={() => {}}>
              <LinearGradient
                colors={feature.gradient as [string, string]}
                className="h-full items-center p-4">
                <View className="h-15 w-15 mb-4 items-center justify-center rounded-full bg-white/10">
                  {feature.icon}
                </View>
                <Text className="mb-2 text-center text-lg font-bold">{feature.title}</Text>
                <Text className="text-center text-sm text-text-secondary">
                  {feature.description}
                </Text>
              </LinearGradient>
            </Card>
          ))}
        </View>
      </View>

      {/* Stats Section */}
      <Card className="mb-8">
        <View className="flex-row justify-around">
          {achievements.map((achievement, index) => (
            <View key={index} className="flex-1 items-center">
              <View className="mb-2 items-center justify-center rounded-xl bg-secondary-light p-3">
                {achievement.icon}
              </View>
              <Text className="mb-1 text-lg font-bold">{achievement.value}</Text>
              <Text className="text-center text-xs uppercase tracking-wider text-text-secondary">
                {achievement.label}
              </Text>
            </View>
          ))}
        </View>
      </Card>

      {/* Testimonials Section */}
      <View className="mb-8">
        <Text className="mb-2 text-center text-2xl font-bold">What Our Users Say</Text>
        <Text className="mb-6 text-center text-sm text-text-secondary">
          Real stories from our community
        </Text>

        <ScrollView horizontal showsHorizontalScrollIndicator={false} className="ml-[-16px] pl-4">
          {testimonials.map((testimonial, index) => (
            <Card key={index} className="mr-4 w-[300px]">
              <View className="mb-4 flex-row items-center">
                <View className="relative mr-4">
                  <Image source={{ uri: testimonial.image }} className="h-14 w-14 rounded-full" />
                  <View className="absolute -left-0.5 -top-0.5 h-[60px] w-[60px] rounded-full border-2 border-primary" />
                </View>

                <View className="flex-1">
                  <Text className="text-lg font-bold">{testimonial.name}</Text>
                  <Text className="text-sm text-text-secondary">{testimonial.role}</Text>
                  <View className="mt-1.5 flex-row gap-0.5">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <Star key={i} color="#f9c04a" size={14} weight="fill" />
                    ))}
                  </View>
                </View>
              </View>

              <Text className="italic text-text-secondary">&quot;{testimonial.text}&quot;</Text>
            </Card>
          ))}
        </ScrollView>
      </View>

      {/* CTA Section */}
      <Card className="mb-6 overflow-hidden p-0">
        <LinearGradient
          colors={['#60A5FA', '#A78BFA', '#22D3EE']}
          className="relative items-center p-8"
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 1 }}>
          <View className="absolute inset-0">
            <View className="h-25 w-25 absolute left-[10%] top-[5%] rounded-full bg-white/5" />
            <View className="absolute bottom-[10%] right-[15%] h-20 w-20 rounded-full bg-white/5" />
            <View className="h-15 w-15 absolute right-[5%] top-[50%] rounded-full bg-white/5" />
          </View>

          <Text className="mb-3 text-center text-2xl font-bold text-white">Get Started Today</Text>
          <Text className="mb-6 text-center text-sm text-white/90">
            Join thousands of others who have transformed their fitness journey
          </Text>

          <Button
            onPress={() => router.push('/sign-up')}
            size="lg"
            className="flex-row items-center gap-3">
            <Text className="text-lg font-bold text-primary-dark">Get Started</Text>
            <ArrowRight color="#000000" size={22} />
          </Button>
        </LinearGradient>
      </Card>

      {/* Footer */}
      <View className="mb-5 items-center py-5">
        <Text className="text-center text-sm text-text-secondary">
          © 2024 FitFlow. All rights reserved.
        </Text>
      </View>
    </ScrollView>
  );
}
